/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yochat.client;

/**
 *
 * @author coulibai
 */
public class clientFrame extends javax.swing.JFrame {

    /**
     * Creates new form clientFrame
     */
    public clientFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane8 = new javax.swing.JDesktopPane();
        tfUsername7 = new javax.swing.JTextField();
        LblClient7 = new javax.swing.JLabel();
        btnConnect7 = new javax.swing.JButton();
        tfAddress7 = new javax.swing.JTextField();
        btnDisconnect7 = new javax.swing.JButton();
        tfPort7 = new javax.swing.JTextField();
        btnClear7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TaMessage = new javax.swing.JTextArea();
        BtnSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaChat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane8.setBackground(new java.awt.Color(101, 132, 148));

        tfUsername7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tfUsername7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfUsername7.setText("Username");
        tfUsername7.setToolTipText("Enter your username");
        tfUsername7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsername7FocusGained(evt);
            }
        });

        LblClient7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LblClient7.setForeground(new java.awt.Color(255, 255, 255));
        LblClient7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblClient7.setText("CLIENT");
        LblClient7.setToolTipText("");
        LblClient7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblClient7.setInheritsPopupMenu(false);

        btnConnect7.setBackground(new java.awt.Color(0, 102, 51));
        btnConnect7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnConnect7.setText("Connect");
        btnConnect7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tfAddress7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfAddress7.setText("IP Address");
        tfAddress7.setToolTipText("Entrer localhost ou IP Addresse");
        tfAddress7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfAddress7FocusGained(evt);
            }
        });

        btnDisconnect7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnDisconnect7.setText("Disconnect");

        tfPort7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tfPort7.setText("Port");

        btnClear7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnClear7.setText("Clear");

        jDesktopPane8.setLayer(tfUsername7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(LblClient7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(btnConnect7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(tfAddress7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(btnDisconnect7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(tfPort7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(btnClear7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane8Layout = new javax.swing.GroupLayout(jDesktopPane8);
        jDesktopPane8.setLayout(jDesktopPane8Layout);
        jDesktopPane8Layout.setHorizontalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane8Layout.createSequentialGroup()
                        .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUsername7)
                            .addComponent(tfAddress7, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(tfPort7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(btnClear7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDisconnect7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConnect7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblClient7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );
        jDesktopPane8Layout.setVerticalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane8Layout.createSequentialGroup()
                .addComponent(LblClient7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane8Layout.createSequentialGroup()
                        .addComponent(btnConnect7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jDesktopPane8Layout.createSequentialGroup()
                        .addComponent(tfUsername7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDisconnect7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAddress7)
                            .addComponent(btnClear7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPort7))))
                .addContainerGap())
        );

        TaMessage.setColumns(20);
        TaMessage.setRows(5);
        jScrollPane2.setViewportView(TaMessage);

        BtnSend.setBackground(new java.awt.Color(0, 102, 51));
        BtnSend.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BtnSend.setText("Send");

        TaChat.setEditable(false);
        TaChat.setBackground(new java.awt.Color(102, 102, 102));
        TaChat.setColumns(20);
        TaChat.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TaChat.setForeground(new java.awt.Color(255, 255, 255));
        TaChat.setRows(5);
        TaChat.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(TaChat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane8)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsername7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsername7FocusGained
        tfUsername.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsername7FocusGained

    private void tfAddress7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAddress7FocusGained
        tfAddress.setText("");       // TODO add your handling code here:
    }//GEN-LAST:event_tfAddress7FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSend;
    private javax.swing.JLabel LblClient;
    private javax.swing.JLabel LblClient1;
    private javax.swing.JLabel LblClient2;
    private javax.swing.JLabel LblClient3;
    private javax.swing.JLabel LblClient4;
    private javax.swing.JLabel LblClient5;
    private javax.swing.JLabel LblClient6;
    private javax.swing.JLabel LblClient7;
    private javax.swing.JTextArea TaChat;
    private javax.swing.JTextArea TaMessage;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnClear3;
    private javax.swing.JButton btnClear4;
    private javax.swing.JButton btnClear5;
    private javax.swing.JButton btnClear6;
    private javax.swing.JButton btnClear7;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnConnect1;
    private javax.swing.JButton btnConnect2;
    private javax.swing.JButton btnConnect3;
    private javax.swing.JButton btnConnect4;
    private javax.swing.JButton btnConnect5;
    private javax.swing.JButton btnConnect6;
    private javax.swing.JButton btnConnect7;
    private javax.swing.JButton btnDisconnect;
    private javax.swing.JButton btnDisconnect1;
    private javax.swing.JButton btnDisconnect2;
    private javax.swing.JButton btnDisconnect3;
    private javax.swing.JButton btnDisconnect4;
    private javax.swing.JButton btnDisconnect5;
    private javax.swing.JButton btnDisconnect6;
    private javax.swing.JButton btnDisconnect7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JDesktopPane jDesktopPane7;
    private javax.swing.JDesktopPane jDesktopPane8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfAddress1;
    private javax.swing.JTextField tfAddress2;
    private javax.swing.JTextField tfAddress3;
    private javax.swing.JTextField tfAddress4;
    private javax.swing.JTextField tfAddress5;
    private javax.swing.JTextField tfAddress6;
    private javax.swing.JTextField tfAddress7;
    private javax.swing.JTextField tfPort;
    private javax.swing.JTextField tfPort1;
    private javax.swing.JTextField tfPort2;
    private javax.swing.JTextField tfPort3;
    private javax.swing.JTextField tfPort4;
    private javax.swing.JTextField tfPort5;
    private javax.swing.JTextField tfPort6;
    private javax.swing.JTextField tfPort7;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JTextField tfUsername1;
    private javax.swing.JTextField tfUsername2;
    private javax.swing.JTextField tfUsername3;
    private javax.swing.JTextField tfUsername4;
    private javax.swing.JTextField tfUsername5;
    private javax.swing.JTextField tfUsername6;
    private javax.swing.JTextField tfUsername7;
    // End of variables declaration//GEN-END:variables
}
